---

- name: Install
  include: install.yml
  tags:
    - install

- name: Configure
  include: configure.yml
  tags:
    - configure

- name: Wait for Kafka to start
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    port: "{{ kafka_port }}"
    state: started
