---

- name: reload supervisor
  command: supervisorctl reload

- name: restart supervisor
  service:
    name: supervisor
    state: restarted


- name: restart kafka
  supervisorctl:
    name: kafka
    state: restarted